# Generated by Django 5.2.3 on 2025-07-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensionistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionista',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
