# Generated by Django 5.2.3 on 2025-07-13 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensionistas', '0002_extensionista_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionista',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extensionista',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
