# Generated by Django 5.2.3 on 2025-07-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('cursos', '0002_remove_curso_descricao_curso_status'),
        ('extensionistas', '0003_extensionista_created_at_extensionista_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='curso',
            name='instrutores',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='extensionistas.extensionista'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
